name: Java CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean install
        continue-on-error: true

      - name: Run tests and capture result
        id: test
        if: always()
        run: TEST_RESULT=$(mvn test) && echo $TEST_RESULT && echo "{test_result}={$TEST_RESULT}" >> $GITHUB_OUTPUT

      - name: Calculate grade
        if: always()
        run: |
          test_result="${{ steps.test.outputs.test_result }}"
          # Count the number of test failures
          num_failures=$(echo "$test_result" | grep -Eo 'Tests run: [0-9]+, Failures: [1-9][0-9]*' | grep -Eo '[1-9][0-9]*' || echo 0)
          # Calculate the grade
          grade=$((10 - num_failures))
          if ((grade < 1)); then
            grade=1
          elif ((grade > 10)); then
            grade=10
          fi
          echo "{grade}={$grade}" >> $GITHUB_OUTPUT

      - name: Display grade
        if: always()
        run: |
          echo "Test grade: ${{ steps.calculate_grade.outputs.grade }}"
